version: '3.8'

services:
  web:
    build: .
    container_name: kiranakhata-pro-web
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=kotatiffin_db
      - DB_USER=vishal_dev
      - DB_PASSWORD=mysecretpassword
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: kiranakhata-pro-db-1
    restart: always
    environment:
      POSTGRES_DB: kotatiffin_db
      POSTGRES_USER: vishal_dev
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana

volumes:
  postgres_data:
  grafanadata: