version: '3.8'

services:
  # 1. Django Backend Container
  web:
    build: .
    container_name: kotatiffin_web
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8089:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=kotatiffin_db
      - DB_USER=vishal_dev
      - DB_PASSWORD=mysecretpassword
      - DATABASE_URL=postgres://vishal_dev:mysecretpassword@db:5432/kotatiffin_db
    depends_on:
      - db

  # 2. PostgreSQL Database Container
  db:
    image: postgres:15-alpine
    container_name: kotatiffin_db
    restart: always
    environment:
      POSTGRES_DB: kotatiffin_db
      POSTGRES_USER: vishal_dev
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 3. Grafana Monitoring Container
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana

volumes:
  postgres_data:
  grafanadata:
  pgdata:
  mysqldata:
  mongodata: