name: Deploy to EC2 via Self-Hosted Runner

on:
  push:
    branches: [ main ] # ya master

jobs:
  deploy:
  # Yahan humne standard runner ki jagah self-hosted set kar diya hai
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Django Migrations & Restart App
        run: |
          # Apne project directory ka path yahan check kar lena
          cd /home/ubuntu/kiranakhata-pro
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          sudo systemctl restart gunicorn
